// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Emits a TOML manifest of the declared Vortex editions.
//!
//! This is the first stage of `cargo xtask generate-editions-docs`: it validates the
//! declarations in `vortex::editions` and dumps them (plus each edition's computed full
//! encoding set) as TOML to the path given as the first argument, conventionally under
//! `target/`. The manifest is a build artifact and is never committed; xtask renders it
//! into the registry section of `docs/specs/editions.md`, which is.
//!
//! Run with: cargo run --example editions_manifest -- <output-path>

use std::error::Error;
use std::fmt::Display;
use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

use vortex::editions::EDITION_DECLARATIONS;
use vortex::editions::EditionSession;

fn main() -> Result<(), Box<dyn Error>> {
    let out_path: PathBuf = std::env::args_os()
        .nth(1)
        .ok_or("usage: editions_manifest <output-path>")?
        .into();

    let editions = EditionSession::empty();
    for declaration in EDITION_DECLARATIONS {
        editions.declare(declaration)?;
    }
    editions.validate()?;

    let mut toml = String::new();
    toml.push_str(
        "# Manifest of the Vortex edition declarations in `vortex/src/editions/`.\n\
         # Generated by `cargo run -p vortex --example editions_manifest`; not committed.\n",
    );
    for edition in editions.editions() {
        writeln!(toml)?;
        writeln!(toml, "[[editions]]")?;
        writeln!(toml, "id = \"{}\"", edition.id)?;
        writeln!(toml, "family = \"{}\"", edition.id.family)?;
        if let Some(version) = edition.min_vortex_version {
            writeln!(toml, "min_vortex_version = \"{version}\"")?;
        }
        let members = editions.encodings_in(&edition.id);
        let added = members
            .iter()
            .filter(|inclusion| inclusion.since == edition.id)
            .map(|inclusion| inclusion.encoding_id);
        write_string_array(&mut toml, "added", added)?;
        write_string_array(
            &mut toml,
            "encodings",
            members.iter().map(|inclusion| inclusion.encoding_id),
        )?;
    }

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&out_path, toml)?;
    Ok(())
}

/// Write a multi-line TOML array of strings. Encoding ids are validated to contain only
/// lowercase ASCII, digits, and `._-`, so no TOML escaping is needed.
fn write_string_array(
    toml: &mut String,
    key: &str,
    values: impl Iterator<Item = impl Display>,
) -> Result<(), Box<dyn Error>> {
    writeln!(toml, "{key} = [")?;
    for value in values {
        writeln!(toml, "    \"{value}\",")?;
    }
    writeln!(toml, "]")?;
    Ok(())
}
