#  SPDX-License-Identifier: Apache-2.0
#  SPDX-FileCopyrightText: Copyright the Vortex contributors

from datetime import date, datetime
from typing import TypeAlias, final

from typing_extensions import override

from .dtype import DType
from .scalar import ScalarPyType

IntoExpr: TypeAlias = Expr | int | float | str | bytes | date | datetime | None

@final
class Expr:
    @override
    def __eq__(self, other: IntoExpr) -> Expr: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @override
    def __ne__(self, other: IntoExpr) -> Expr: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def __lt__(self, other: IntoExpr) -> Expr: ...
    def __le__(self, other: IntoExpr) -> Expr: ...
    def __gt__(self, other: IntoExpr) -> Expr: ...
    def __ge__(self, other: IntoExpr) -> Expr: ...
    def __and__(self, other: IntoExpr) -> Expr: ...
    def __or__(self, other: IntoExpr) -> Expr: ...
    def __add__(self, other: IntoExpr) -> Expr: ...
    def __sub__(self, other: IntoExpr) -> Expr: ...
    def __mul__(self, other: IntoExpr) -> Expr: ...
    def __truediv__(self, other: IntoExpr) -> Expr: ...
    def __invert__(self) -> Expr: ...
    def __getitem__(self, field: str) -> Expr: ...

def column(name: str) -> Expr: ...
def root() -> Expr: ...
def literal(dtype: DType, value: ScalarPyType) -> Expr: ...
def not_(child: Expr) -> Expr: ...
def and_(left: Expr, right: Expr) -> Expr: ...
def or_(left: Expr, right: Expr) -> Expr: ...
def cast(child: Expr, dtype: DType) -> Expr: ...
def is_null(child: Expr) -> Expr: ...
def is_not_null(child: Expr) -> Expr: ...
def between(
    child: Expr, lower: IntoExpr, upper: IntoExpr, *, lower_strict: bool = False, upper_strict: bool = False
) -> Expr: ...
def like(child: Expr, pattern: Expr | str, *, negated: bool = False, case_insensitive: bool = False) -> Expr: ...
def fill_null(child: Expr, fill_value: IntoExpr) -> Expr: ...
def get_item(field: str, child: Expr) -> Expr: ...
def select(fields: list[str], child: Expr) -> Expr: ...
def select_exclude(fields: list[str], child: Expr) -> Expr: ...
def pack(fields: dict[str, Expr], *, nullable: bool = False) -> Expr: ...
def merge(children: list[Expr]) -> Expr: ...
def case_when(condition: Expr, then: Expr, otherwise: Expr | None = None) -> Expr: ...
def zip_(condition: Expr, if_true: Expr, if_false: Expr) -> Expr: ...
def mask(child: Expr, mask: Expr) -> Expr: ...
def list_contains(list: Expr, value: IntoExpr) -> Expr: ...
def list_length(child: Expr) -> Expr: ...
def list_sum(child: Expr) -> Expr: ...
def byte_length(child: Expr) -> Expr: ...
