// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use anyhow::Context;
use serde::Deserialize;
use xshell::Shell;
use xshell::cmd;

/// Header comment stamped on every fully generated page.
static GENERATED_HEADER: &str = "<!-- Generated by `cargo xtask generate-editions-docs` from the \
                                 declarations in `vortex/src/editions/`; do not edit. -->";

/// The manifest emitted by `cargo run -p vortex --example editions_manifest`.
#[derive(Deserialize)]
struct Manifest {
    editions: Vec<ManifestEdition>,
}

#[derive(Deserialize)]
struct ManifestEdition {
    id: String,
    family: String,
    /// Absent for draft editions.
    min_vortex_version: Option<String>,
    /// The encodings that join the family at this edition.
    added: Vec<String>,
    /// The edition's full computed encoding set.
    encodings: Vec<String>,
}

impl ManifestEdition {
    fn status(&self) -> &'static str {
        match self.min_vortex_version {
            Some(_) => "frozen",
            None => "draft",
        }
    }

    fn min_reader(&self) -> &str {
        self.min_vortex_version.as_deref().unwrap_or("—")
    }

    /// This edition's page filename within `docs/specs/editions/`.
    fn file_name(&self) -> String {
        format!("{}.md", self.id)
    }

    /// A link to this edition's page from a sibling page in `docs/specs/editions/`.
    fn sibling_link(&self) -> String {
        format!("[`{}`]({})", self.id, self.file_name())
    }
}

/// Regenerate the edition registry pages under `docs/specs/editions/` (an index page plus
/// one page per edition) from the edition declarations in the `vortex` crate, via a TOML
/// manifest written under `target/`.
pub fn generate_editions_docs(profile: Option<String>) -> anyhow::Result<()> {
    let sh = Shell::new()?;
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..");
    sh.change_dir(&root);

    let manifest_path = root.join("target/editions-manifest.toml");
    let profile_args: Vec<String> = profile
        .into_iter()
        .flat_map(|p| ["--profile".to_string(), p])
        .collect();
    cmd!(
        sh,
        "cargo run {profile_args...} -p vortex --example editions_manifest -- {manifest_path}"
    )
    .run()?;

    let manifest: Manifest = toml::from_str(&fs::read_to_string(&manifest_path)?)
        .context("parsing the editions manifest")?;

    // The since-edition of every encoding, for the per-edition membership tables.
    let since: BTreeMap<&String, &ManifestEdition> = manifest
        .editions
        .iter()
        .flat_map(|edition| {
            edition
                .added
                .iter()
                .map(move |encoding| (encoding, edition))
        })
        .collect();

    // The registry directory is wholly generated: drop stale pages before writing.
    let registry_dir = root.join("docs/specs/editions");
    fs::create_dir_all(&registry_dir)?;
    for entry in fs::read_dir(&registry_dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|ext| ext == "md") {
            fs::remove_file(path)?;
        }
    }

    fs::write(registry_dir.join("index.md"), render_index(&manifest)?)?;
    for edition in &manifest.editions {
        fs::write(
            registry_dir.join(edition.file_name()),
            render_edition(edition, &since)?,
        )?;
    }
    println!(
        "regenerated the edition registry in {}",
        registry_dir.display()
    );

    Ok(())
}

/// Render the registry index page, `docs/specs/editions/index.md`.
fn render_index(manifest: &Manifest) -> anyhow::Result<String> {
    let mut md = String::new();
    writeln!(md, "{GENERATED_HEADER}\n\n# Edition registry\n")?;
    writeln!(
        md,
        "Every Vortex [edition](../editions.md), with one page per edition.\n\n\
         ## Editions\n\n\
         | Edition | Status | Minimum Vortex reader | Encodings |\n\
         | --- | --- | --- | --- |"
    )?;
    for edition in &manifest.editions {
        writeln!(
            md,
            "| {} | {} | {} | {} |",
            edition.sibling_link(),
            edition.status(),
            edition.min_reader(),
            edition.encodings.len(),
        )?;
    }

    writeln!(
        md,
        "\nA draft edition is still being assembled: its encoding set may change and it \
         carries no compatibility guarantee until it is frozen.\n\n\
         ## Encoding index\n\n\
         Each encoding lists the edition it first joined; it is a member of every later \
         edition of the same family. The minimum Vortex reader is the one declared by that \
         edition.\n\n\
         | Encoding | Since edition | Minimum Vortex reader |\n\
         | --- | --- | --- |"
    )?;
    let mut rows: Vec<(&String, &ManifestEdition)> = manifest
        .editions
        .iter()
        .flat_map(|edition| {
            edition
                .added
                .iter()
                .map(move |encoding| (encoding, edition))
        })
        .collect();
    // An encoding joins exactly one edition, so its id alone is a total order.
    rows.sort_by(|(a, _), (b, _)| a.cmp(b));
    for (encoding, edition) in rows {
        writeln!(
            md,
            "| `{}` | {} | {} |",
            encoding,
            edition.sibling_link(),
            edition.min_reader(),
        )?;
    }

    writeln!(md, "\n```{{toctree}}\n---\nhidden:\n---\n")?;
    for edition in &manifest.editions {
        writeln!(md, "{}", edition.id)?;
    }
    writeln!(md, "```")?;
    Ok(md)
}

/// Render one edition's page, `docs/specs/editions/<id>.md`.
fn render_edition(
    edition: &ManifestEdition,
    since: &BTreeMap<&String, &ManifestEdition>,
) -> anyhow::Result<String> {
    let mut md = String::new();
    writeln!(md, "{GENERATED_HEADER}\n\n# {}\n", edition.id)?;
    match &edition.min_vortex_version {
        Some(version) => writeln!(
            md,
            "An edition of the `{}` family. Frozen — readable by Vortex {version} and newer.",
            edition.family
        )?,
        None => writeln!(
            md,
            "A **draft** edition of the `{}` family — still being assembled, it carries no \
             compatibility guarantee yet.",
            edition.family
        )?,
    }

    let added = match edition.added.len() {
        1 => "1 encoding".to_string(),
        n => format!("{n} encodings"),
    };
    writeln!(
        md,
        "\nAdds {added}: {}",
        edition
            .added
            .iter()
            .map(|encoding| format!("`{encoding}`"))
            .collect::<Vec<_>>()
            .join(", ")
    )?;

    writeln!(
        md,
        "\n## Encodings ({})\n\n\
         | Encoding | Since edition |\n\
         | --- | --- |",
        edition.encodings.len()
    )?;
    for encoding in &edition.encodings {
        let joined = since
            .get(encoding)
            .map(|e| e.sibling_link())
            .unwrap_or_else(|| "—".to_string());
        writeln!(md, "| `{encoding}` | {joined} |")?;
    }
    Ok(md)
}
